on:
  pull_request:
    paths:
      - "web/**"
      - ".github/**"
jobs:
  build_and_deploy_web_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./web
#      - run: npm test
#        working-directory: ./web
#      - run: cp .env.ci .env.local
#        working-directory: ./web
      - run: npm run build
        working-directory: ./web